.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "TEST\.SH" "1" "November 2016" "" ""
.
.SH "NAME"
\fBtest.sh\fR \-\- Test script
.
.SH "SYNOPSIS"
\fBtest\.sh\fR [\-hVfi]
.
.SH "OPTIONS"
  \fB\-h, \-\-help\fR              display this message
  \fB\-V, \-\-version\fR           output version
  \fB\-f, \-\-functionals\fR       run functional tests
  \fB\-i, \-\-integrations\fR      run integration tests
.
.SH "USAGE"
  Follow sample test\.sh script for getting options, and where add your tests
.
.P
  $ test\.sh \-\-functionals
  runs functional tests and reports how many tests pass and how many tests fail
.
.P
  $ test\.sh \-\-integrations
  runs integration tests and reports how many tests pass and how many tests fail
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Alessandra Bilardi \fIalessandra\.bilardi@gmail\.com\fR
.
.IP "" 0
.
.SH "REPORTING BUGS"
.
.IP "\(bu" 4
https://github\.com/bilardi/bash\-utils/issues
.
.IP "" 0
.
.SH "SEE ALSO"
  \fBregexp\fR(1)
.
.SH "LICENSE"
  MIT (C) Copyright Alessandra Bilardi 2016